//! Core message types shared across the whole application.
//!
//! `Role` and `ChatMessage` are the atoms of every conversation. They flow
//! upward through `Conversation` → `Session` → the OpenRouter wire format
//! (`dto/openrouter.rs`), and are persisted verbatim to `messages.json` on
//! disk. Keeping them in a separate module avoids circular imports between the
//! model layer and the wire-format layer.

use serde::{Deserialize, Serialize};

/// Which participant authored a message.
///
/// Serialised as lowercase strings (`"system"`, `"user"`, `"assistant"`) to
/// match the OpenRouter / OpenAI chat-completions wire format.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// The hidden prompt that sets the assistant's behaviour. Always the first
    /// message in a conversation; rebuilt from embedded resources + MEMORY.md
    /// on every session load via `Session::rebuild_system`.
    System,
    /// A message typed by the human in the TUI.
    User,
    /// A response generated by the model (streamed or non-streamed).
    Assistant,
}

impl Role {
    /// Short display label used in the TUI chat view.
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "sys",
            Role::User => "you",
            Role::Assistant => "ai",
        }
    }
}

/// A single turn in a conversation: who spoke and what they said.
///
/// Serialised to / from JSON so it can be stored in `messages.json` and sent
/// directly in `ChatRequest::messages` without a mapping step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    pub content: String,
}

impl ChatMessage {
    /// Construct a message, accepting any `Into<String>` for convenience.
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
        }
    }
}
