//! Core message types shared across the whole application.
//!
//! `Role` and `ChatMessage` are the atoms of every conversation. They flow
//! upward through `Conversation` → `Session` → the OpenRouter wire format
//! (`dto/openrouter.rs`), and are persisted verbatim to `messages.json` on
//! disk. Keeping them in a separate module avoids circular imports between the
//! model layer and the wire-format layer.

use serde::{Deserialize, Serialize};

/// Prefix marking a tool result as a harness-internal message (e.g. the silent
/// "plan first" nudge) that should be fed to the model but NOT shown in the
/// transcript. An invisible char so it never affects what the model reads.
pub const PLAN_NUDGE_MARK: &str = "\u{2063}";

/// Marks the boundary in a System message between the STABLE cached head and
/// the volatile (per-session-changing) tail (project file listing, awareness
/// summary). `to_wire` puts the cache breakpoint on the head only.
pub const CACHE_SPLIT_MARK: &str = "\u{2062}\u{2061}";

/// Which participant authored a message.
///
/// Serialised as lowercase strings (`"system"`, `"user"`, `"assistant"`) to
/// match the OpenRouter / OpenAI chat-completions wire format.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// The hidden prompt that sets the assistant's behaviour. Always the first
    /// message in a conversation; rebuilt from embedded resources + MEMORY.md
    /// on every session load via `Session::rebuild_system`.
    System,
    /// A message typed by the human in the TUI.
    User,
    /// A response generated by the model (streamed or non-streamed).
    Assistant,
    /// The result of running a tool, fed back to the model. Carries a
    /// `tool_call_id` pointing at the assistant `tool_calls` entry it answers.
    Tool,
}

impl Role {
    /// Short display label used in the TUI chat view.
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "sys",
            Role::User => "you",
            Role::Assistant => "ai",
            Role::Tool => "tool",
        }
    }
}

/// The function-call payload inside a [`ToolCall`]: the tool name plus its
/// arguments as a JSON-encoded string (OpenAI/OpenRouter send `arguments` as a
/// stringified JSON object, not a nested object).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// One tool call requested by the assistant. `id` correlates the eventual
/// `tool` result message back to this call; `kind` is always `"function"`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type", default)]
    pub kind: String, // "function"
    pub function: FunctionCall,
}

/// Parse out tool calls a model emitted as TEXT in its content rather than via
/// the native OpenAI-style `tool_calls` field. Budget / gpt-oss / GLM routes
/// (and Hermes/Qwen/ChatML-trained models generally) tend to write a call as a
/// `<tool_call>{"name": "...", "arguments": {...}}</tool_call>` span in plain
/// text; without this fallback such calls render as literal text and never run.
///
/// Scans `content` for `<tool_call>` … `</tool_call>` spans. Each `</tool_call>`
/// close tag is paired with the NEAREST `<tool_call>` open that precedes it
/// (within the not-yet-consumed region), so a stray/unclosed open tag before a
/// valid block never swallows the valid block's call. Trims inner text and
/// parses it as JSON. A span counts as a tool call only when the JSON is an
/// object with a non-empty string `name` and an `arguments` (or `parameters`)
/// field. The arguments are normalised to a JSON-encoded string (mirroring how
/// the wire format carries `FunctionCall.arguments`): a JSON string is used
/// verbatim, a JSON object is stringified, and any other value (number, bool,
/// null, array) or a missing key degrades to `"{}"`.
///
/// Returns `(cleaned_content, calls)`. Successfully-parsed spans are removed
/// from the content (leading/trailing whitespace trimmed, 3+ newline runs
/// collapsed to 2); malformed or non-tool-call spans are SKIPPED and left in
/// the content so the user still sees the model's raw attempt. When nothing
/// parses, the content is returned unchanged with an empty vec.
pub fn extract_text_tool_calls(content: &str) -> (String, Vec<ToolCall>) {
    const OPEN: &str = "<tool_call>";
    const CLOSE: &str = "</tool_call>";

    let mut calls: Vec<ToolCall> = Vec::new();
    // Spans (byte ranges over `content`, including the tags) that parsed
    // successfully and must be stripped from the cleaned output.
    let mut remove: Vec<(usize, usize)> = Vec::new();

    let mut search_from = 0usize;
    while let Some(rel_close) = content[search_from..].find(CLOSE) {
        let close_start = search_from + rel_close;
        let close_end = close_start + CLOSE.len();

        // Within the not-yet-consumed region up to this close tag, find the
        // NEAREST (rightmost) preceding open tag.
        let region = &content[search_from..close_start];
        match region.rfind(OPEN) {
            Some(rel_open) => {
                let open_start = search_from + rel_open;
                let inner_start = open_start + OPEN.len();
                let inner = content[inner_start..close_start].trim();
                if let Some((name, arguments)) = parse_tool_call_json(inner) {
                    calls.push(ToolCall {
                        id: format!("text_call_{}", calls.len()),
                        kind: "function".to_string(),
                        function: FunctionCall { name, arguments },
                    });
                    remove.push((open_start, close_end));
                }
                // Whether it parsed or not, advance past this close tag.
                search_from = close_end;
            }
            None => {
                // No open tag precedes this close — orphan close; skip it.
                search_from = close_end;
            }
        }
    }

    if calls.is_empty() {
        return (content.to_string(), Vec::new());
    }

    // Rebuild the content with the parsed spans removed (ranges are in order
    // and non-overlapping since we scan left to right).
    let mut cleaned = String::with_capacity(content.len());
    let mut cursor = 0usize;
    for (start, end) in remove {
        cleaned.push_str(&content[cursor..start]);
        cursor = end;
    }
    cleaned.push_str(&content[cursor..]);

    let cleaned = collapse_blank_runs(cleaned.trim());
    (cleaned, calls)
}

/// Parse one `<tool_call>` inner JSON blob into `(name, arguments_string)`.
/// Returns `None` unless it is an object with a non-empty string `name` and an
/// `arguments` or `parameters` field (or `name` alone, which yields `"{}"`).
fn parse_tool_call_json(inner: &str) -> Option<(String, String)> {
    let value: serde_json::Value = serde_json::from_str(inner).ok()?;
    let obj = value.as_object()?;
    let name = obj.get("name")?.as_str()?;
    if name.is_empty() {
        return None;
    }
    let args_value = obj.get("arguments").or_else(|| obj.get("parameters"));
    let arguments = match args_value {
        // A JSON string is used verbatim (already stringified JSON / raw text).
        Some(serde_json::Value::String(s)) => s.clone(),
        // A JSON object is stringified into our String-encoded form.
        Some(v @ serde_json::Value::Object(_)) => serde_json::to_string(v).ok()?,
        // Scalars (number, bool, null) and arrays are not valid argument bags;
        // degrade to an empty object rather than emitting e.g. "5" or "null".
        Some(_) => "{}".to_string(),
        // name present but no arguments/parameters → empty object.
        None => "{}".to_string(),
    };
    Some((name.to_string(), arguments))
}

/// Collapse any run of 3+ consecutive newlines into exactly 2, leaving other
/// whitespace untouched. Used to tidy the gap left behind when a `<tool_call>`
/// span is removed from between blocks of prose.
fn collapse_blank_runs(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut newline_run = 0usize;
    for ch in s.chars() {
        if ch == '\n' {
            newline_run += 1;
            if newline_run <= 2 {
                out.push(ch);
            }
        } else {
            newline_run = 0;
            out.push(ch);
        }
    }
    out
}

/// A single turn in a conversation: who spoke and what they said.
///
/// Serialised to / from JSON so it can be stored in `messages.json` and sent
/// directly in `ChatRequest::messages` without a mapping step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    pub content: String,
    /// Present on an assistant message that requested one or more tool calls.
    /// Serialised as the OpenAI/OpenRouter `tool_calls` array; omitted entirely
    /// on plain messages so existing `messages.json` files stay compatible.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Present on a `tool`-role message: the id of the assistant `tool_calls`
    /// entry this message answers. Omitted on every other message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Display-only reasoning/thinking text accumulated from the model's
    /// `delta.reasoning` channel during streaming. `#[serde(skip)]` means it is
    /// NEVER serialised — not into a `ChatRequest` body nor `messages.json` — and
    /// always defaults to `None` on deserialise. This keeps reasoning purely a
    /// render-time concern: it shows above the answer but never re-enters the
    /// conversation the model sees, and never touches disk.
    #[serde(skip)]
    pub reasoning: Option<String>,
}

impl ChatMessage {
    /// Construct a plain message, accepting any `Into<String>` for convenience.
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
            tool_calls: None,
            tool_call_id: None,
            reasoning: None,
        }
    }

    /// Construct an assistant message that requested tool calls. `content` may
    /// be empty (the model often emits tool calls with no accompanying text).
    pub fn assistant_with_tools(content: String, tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: Role::Assistant,
            content,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
            reasoning: None,
        }
    }

    /// Construct a `tool`-role result message answering a specific tool call.
    pub fn tool_result(tool_call_id: String, content: String) -> Self {
        Self {
            role: Role::Tool,
            content,
            tool_calls: None,
            tool_call_id: Some(tool_call_id),
            reasoning: None,
        }
    }

    /// Attach a display-only reasoning block (builder style). An empty/`None`
    /// reasoning leaves the field `None` so no empty thinking block renders.
    /// Used at assistant-commit time to fold the streamed reasoning buffer onto
    /// the message before it enters the conversation.
    pub fn with_reasoning(mut self, reasoning: Option<String>) -> Self {
        self.reasoning = reasoning.filter(|r| !r.is_empty());
        self
    }
}

#[cfg(test)]
mod text_tool_call_tests {
    use super::*;

    #[test]
    fn single_block_object_arguments() {
        let content =
            r#"<tool_call>{"name": "read", "arguments": {"path": "ARCHITECTURE.md"}}</tool_call>"#;
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].id, "text_call_0");
        assert_eq!(calls[0].kind, "function");
        assert_eq!(calls[0].function.name, "read");
        assert_eq!(calls[0].function.arguments, r#"{"path":"ARCHITECTURE.md"}"#);
    }

    #[test]
    fn parameters_alias() {
        let content =
            r#"<tool_call>{"name": "list", "parameters": {"dir": "src"}}</tool_call>"#;
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "list");
        assert_eq!(calls[0].function.arguments, r#"{"dir":"src"}"#);
    }

    #[test]
    fn arguments_already_json_string() {
        // `arguments` is itself a JSON string holding stringified JSON — used verbatim.
        let content =
            r#"<tool_call>{"name": "bash", "arguments": "{\"cmd\": \"ls\"}"}</tool_call>"#;
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "bash");
        assert_eq!(calls[0].function.arguments, r#"{"cmd": "ls"}"#);
    }

    #[test]
    fn two_blocks_in_one_message() {
        let content = concat!(
            r#"<tool_call>{"name": "read", "arguments": {"path": "a"}}</tool_call>"#,
            "\n",
            r#"<tool_call>{"name": "read", "arguments": {"path": "b"}}</tool_call>"#,
        );
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].id, "text_call_0");
        assert_eq!(calls[1].id, "text_call_1");
        assert_eq!(calls[0].function.arguments, r#"{"path":"a"}"#);
        assert_eq!(calls[1].function.arguments, r#"{"path":"b"}"#);
    }

    #[test]
    fn malformed_json_skipped_and_left_in_content() {
        let content = r#"<tool_call>{"name": "read", "arguments": }</tool_call>"#;
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert!(calls.is_empty());
        // Skipped block stays in the content verbatim.
        assert_eq!(cleaned, content);
    }

    #[test]
    fn surrounding_prose_preserved() {
        let content = concat!(
            "Let me read that file.\n\n",
            r#"<tool_call>{"name": "read", "arguments": {"path": "x"}}</tool_call>"#,
            "\n\nDone.",
        );
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "read");
        assert_eq!(cleaned, "Let me read that file.\n\nDone.");
    }

    #[test]
    fn no_tool_call_present() {
        let content = "Just a normal answer with no tool calls at all.";
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert!(calls.is_empty());
        assert_eq!(cleaned, content);
    }

    #[test]
    fn nested_braces_in_arguments() {
        let content = concat!(
            r#"<tool_call>{"name": "edit", "arguments": {"path": "f", "#,
            r#""replace": {"from": {"a": 1}, "to": {"b": 2}}}}</tool_call>"#,
        );
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "edit");
        // Re-parse the stringified arguments to confirm the nesting survived.
        let v: serde_json::Value =
            serde_json::from_str(&calls[0].function.arguments).unwrap();
        assert_eq!(v["replace"]["from"]["a"], 1);
        assert_eq!(v["replace"]["to"]["b"], 2);
    }

    #[test]
    fn whitespace_inside_tags_tolerated() {
        let content = "<tool_call>\n  {\n  \"name\": \"read\",\n  \"arguments\": {\"path\": \"y\"}\n  }\n</tool_call>";
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(cleaned, "");
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.arguments, r#"{"path":"y"}"#);
    }

    #[test]
    fn stray_open_before_valid_block_still_parses() {
        // A stray <tool_call> with no matching close precedes a complete valid
        // block. The close of the valid block must re-anchor to the valid
        // block's own open; the stray open is left in content as text.
        let content = concat!(
            "stray <tool_call> then a real ",
            r#"<tool_call>{"name":"read","arguments":{"path":"x"}}</tool_call>"#,
        );
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(calls.len(), 1, "exactly one call must be parsed");
        assert_eq!(calls[0].function.name, "read");
        // The valid block's span is removed from content; the stray open tag
        // text may remain but the parsed block must not be present.
        assert!(
            !cleaned.contains(r#"{"name":"read""#),
            "parsed block should be stripped from content"
        );
    }

    #[test]
    fn scalar_arguments_coerced_to_empty_object() {
        // `arguments` is a bare number — not a valid argument bag.
        // Must be coerced to "{}" rather than emitting "5".
        let content = r#"<tool_call>{"name":"ping","arguments":5}</tool_call>"#;
        let (cleaned, calls) = extract_text_tool_calls(content);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "ping");
        assert_eq!(calls[0].function.arguments, "{}");
        assert_eq!(cleaned, "");
    }
}
