//! Core message types shared across the whole application.
//!
//! `Role` and `ChatMessage` are the atoms of every conversation. They flow
//! upward through `Conversation` → `Session` → the OpenRouter wire format
//! (`dto/openrouter.rs`), and are persisted verbatim to `messages.json` on
//! disk. Keeping them in a separate module avoids circular imports between the
//! model layer and the wire-format layer.

use serde::{Deserialize, Serialize};

/// Prefix marking a tool result as a harness-internal message (e.g. the silent
/// "plan first" nudge) that should be fed to the model but NOT shown in the
/// transcript. An invisible char so it never affects what the model reads.
pub const PLAN_NUDGE_MARK: &str = "\u{2063}";

/// Which participant authored a message.
///
/// Serialised as lowercase strings (`"system"`, `"user"`, `"assistant"`) to
/// match the OpenRouter / OpenAI chat-completions wire format.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// The hidden prompt that sets the assistant's behaviour. Always the first
    /// message in a conversation; rebuilt from embedded resources + MEMORY.md
    /// on every session load via `Session::rebuild_system`.
    System,
    /// A message typed by the human in the TUI.
    User,
    /// A response generated by the model (streamed or non-streamed).
    Assistant,
    /// The result of running a tool, fed back to the model. Carries a
    /// `tool_call_id` pointing at the assistant `tool_calls` entry it answers.
    Tool,
}

impl Role {
    /// Short display label used in the TUI chat view.
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "sys",
            Role::User => "you",
            Role::Assistant => "ai",
            Role::Tool => "tool",
        }
    }
}

/// The function-call payload inside a [`ToolCall`]: the tool name plus its
/// arguments as a JSON-encoded string (OpenAI/OpenRouter send `arguments` as a
/// stringified JSON object, not a nested object).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// One tool call requested by the assistant. `id` correlates the eventual
/// `tool` result message back to this call; `kind` is always `"function"`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type", default)]
    pub kind: String, // "function"
    pub function: FunctionCall,
}

/// A single turn in a conversation: who spoke and what they said.
///
/// Serialised to / from JSON so it can be stored in `messages.json` and sent
/// directly in `ChatRequest::messages` without a mapping step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    pub content: String,
    /// Present on an assistant message that requested one or more tool calls.
    /// Serialised as the OpenAI/OpenRouter `tool_calls` array; omitted entirely
    /// on plain messages so existing `messages.json` files stay compatible.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Present on a `tool`-role message: the id of the assistant `tool_calls`
    /// entry this message answers. Omitted on every other message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Display-only reasoning/thinking text accumulated from the model's
    /// `delta.reasoning` channel during streaming. `#[serde(skip)]` means it is
    /// NEVER serialised — not into a `ChatRequest` body nor `messages.json` — and
    /// always defaults to `None` on deserialise. This keeps reasoning purely a
    /// render-time concern: it shows above the answer but never re-enters the
    /// conversation the model sees, and never touches disk.
    #[serde(skip)]
    pub reasoning: Option<String>,
}

impl ChatMessage {
    /// Construct a plain message, accepting any `Into<String>` for convenience.
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
            tool_calls: None,
            tool_call_id: None,
            reasoning: None,
        }
    }

    /// Construct an assistant message that requested tool calls. `content` may
    /// be empty (the model often emits tool calls with no accompanying text).
    pub fn assistant_with_tools(content: String, tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: Role::Assistant,
            content,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
            reasoning: None,
        }
    }

    /// Construct a `tool`-role result message answering a specific tool call.
    pub fn tool_result(tool_call_id: String, content: String) -> Self {
        Self {
            role: Role::Tool,
            content,
            tool_calls: None,
            tool_call_id: Some(tool_call_id),
            reasoning: None,
        }
    }

    /// Attach a display-only reasoning block (builder style). An empty/`None`
    /// reasoning leaves the field `None` so no empty thinking block renders.
    /// Used at assistant-commit time to fold the streamed reasoning buffer onto
    /// the message before it enters the conversation.
    pub fn with_reasoning(mut self, reasoning: Option<String>) -> Self {
        self.reasoning = reasoning.filter(|r| !r.is_empty());
        self
    }
}
